---
- name: "Install required packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - unzip
      - tar
      - apt-transport-https
      - btrfs-progs
      - libseccomp2
      - util-linux