---
- name: "Create SSH user .kube directory"
  become: yes
  become_user: "{{ ansible_user_id }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: "Copy admin conf to .kube"
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user_id }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"